parameters:
    tables.poll_votes: %core.table_prefix%poll_votes

services:
    clausi.pollvoters.controller:
        class: clausi\pollvoters\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    clausi.pollvoters.listener:
        class: clausi\pollvoters\event\main_listener
        arguments:
            - @controller.helper
            - @dbal.conn
            - @template
            - @auth
        tags:
            - { name: event.listener }
